// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlbtoemirvuqwbwuljck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sYnRvZW1pcnZ1cXdid3VsamNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzYwMjcsImV4cCI6MjA2NTkxMjAyN30.w0GRSxCW-Sa_Kog6cGL3kmzi30LDdhfN7BwFm0uj-L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);